#!/bin/sh

#load="$(hostname -i | awk '{ print $1 }')"
load="$(curl http://checkip.amazonaws.com 2>/dev/null)"

if [ -z $load ];
then
  load="no internet"
fi

# full text
echo "$load"

# short text
echo "$load"
